-- Q1. What is the total revenue generated by male vs. female customers?

SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer_data
GROUP BY gender;





-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT 
    customer_id AS Customer_ID,
    purchase_amount AS Purchase_Amount
FROM
    customer_data
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer_data);





-- Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased AS Item_Purchased,
    ROUND(AVG(review_rating), 2) AS Average_Product_Rating
FROM
    customer_data
GROUP BY item_purchased
ORDER BY Average_Product_Rating DESC
LIMIT 5;





-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT 
    shipping_type AS Shipping_Type,
    ROUND(AVG(purchase_amount), 2) AS Purchase_Amount
FROM
    customer_data
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;





-- 5. Do subscribed customers spend more? Compare average spend and total revenue 

SELECT 
    subscription_status AS Subcription_Status,
    COUNT(customer_id) AS Total_Customers,
    ROUND(AVG(purchase_amount), 2) AS Average_Spend,
    ROUND(SUM(purchase_amount), 2) AS Total_Revenue
FROM
    customer_data
GROUP BY subscription_status
ORDER BY Total_Revenue , Average_Spend;





-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased as Item_Purchased,
    ROUND(SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) * 100 / COUNT(*),
            2) AS Discount_Rate
FROM
    customer_data
GROUP BY item_purchased
ORDER BY Discount_Rate DESC
LIMIT 5;
 
 
 
 
 
-- Q7. Segment customers into New, Returning, and Loyal based on their total 

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_Segment
    FROM customer_data
)

SELECT
    Customer_Segment,
    COUNT(*) AS Number_Of_Customers
FROM customer_type
GROUP BY Customer_Segment
ORDER BY Customer_Segment;





-- Q8. What are the top 3 most purchased products within each category? 

WITH Item_Count AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS Total_Orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS Item_Rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT
    Item_Rank,
    category AS Category,
    item_purchased AS Item_Purchase,
    Total_Orders
FROM Item_Count
WHERE Item_Rank <= 3;





-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status AS Subcription_Status,
    COUNT(customer_id) AS Repeat_Buyers
FROM
    customer_data
WHERE
    previous_purchases > 5
GROUP BY subscription_status;





-- Q10. What is the revenue contribution of each age group? 

SELECT 
    age_group as Age_Group,
    SUM(purchase_amount) AS Total_Revenue
FROM customer_data
GROUP BY age_group
ORDER BY Total_Revenue DESC;





-- Who are the TOP 10 customers

SELECT
customer_id,
SUM(purchase_amount) AS lifetime_value
FROM customer_data
GROUP BY customer_id
ORDER BY lifetime_value DESC
LIMIT 10;





-- Descibe the revenue by seasonal treand

SELECT
season,
SUM(purchase_amount) AS revenue
FROM customer_data
GROUP BY season
ORDER BY revenue DESC;